# app/config/security.yml
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: %security_admin_pass%
                        roles: 'ROLE_ADMIN'

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login

            logout:       true
            anonymous:    true

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/protected, role: ROLE_ADMIN }