parameters:

services:
    app.sale.mailer:
        class: AppBundle\Service\SaleMailer
        arguments:
            - @mailer
            - %base_url%
            - %mailer_user%
            - %vendor_email%

    app.service.mailchimp:
        class: AppBundle\Service\MailChimp
        arguments:
            - %mailchimp_api_key%
            - %mailchimp_addon_list_map%
            - %mailchimp_api_dc%
            - %mailchimp_enabled%